//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentePersonal
    {
        public int AntPer_Numero { get; set; }
        public int AntPer_Antecedende_Codigo { get; set; }
        public int AntPer_Entrada_Numero { get; set; }
        public string AntPer_Diagnostico { get; set; }
        public string AntPer_Observacion { get; set; }
    
        public virtual AntecedentesP AntecedentesP { get; set; }
        public virtual Atencion_Historia Atencion_Historia { get; set; }
    }
}
