//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecednteFamiliar
    {
        public int AntFam_Numero { get; set; }
        public int AntFam_Enfermedad_Codigo { get; set; }
        public int AntFam_Entrada_Numero { get; set; }
        public string AntFam_Parentesco { get; set; }
        public bool AntFam_Mortalidad { get; set; }
    
        public virtual AntecedentesF AntecedentesF { get; set; }
        public virtual Atencion_Historia Atencion_Historia { get; set; }
    }
}
