//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antropometria
    {
        public int Antr_Codigo { get; set; }
        public Nullable<int> Antr__NumeroAtencion { get; set; }
        public string Antr_Peso { get; set; }
        public string Antr_Talla { get; set; }
        public string Antr_IMC { get; set; }
        public string Antr_PesoIdeal { get; set; }
        public string Antr_ExcesoPeso { get; set; }
    
        public virtual Atencion_Historia Atencion_Historia { get; set; }
    }
}
