//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frecuencia_Consmo
    {
        public int FreCon_Codigo { get; set; }
        public Nullable<int> FreCon_CodAlimento { get; set; }
        public Nullable<int> FreCon_NumeroAtencion { get; set; }
        public string FreCon_Diario { get; set; }
        public string FreCon_Semanal { get; set; }
        public string FreCon_Quincenal { get; set; }
        public string FreCon_Mensual { get; set; }
        public string FreCon_Nunca { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual Atencion_Historia Atencion_Historia { get; set; }
    }
}
