//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabitoDetalle
    {
        public int HabPac_Habito_Codigo { get; set; }
        public int HabPac_Entrada_Numero { get; set; }
        public string HabPac_Caracteristica { get; set; }
        public string HabPac_Frecuencia { get; set; }
        public string HabPac_Tiempo { get; set; }
        public string HabPac_Observacion { get; set; }
    
        public virtual Atencion_Historia Atencion_Historia { get; set; }
        public virtual HABITOS HABITOS { get; set; }
    }
}
