//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial_Peso
    {
        public int HistPes_Codigo { get; set; }
        public Nullable<int> HistPes_NumeroAtencion { get; set; }
        public string HistPes_EdadSobrepeso { get; set; }
        public string HistPes_Problema { get; set; }
        public string HistPes_PesoMaximo { get; set; }
        public string HistPes_PesoMinimo { get; set; }
        public int Entr_Numero { get; set; }
    }
}
