//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public string Medic_TipoIdentificacion { get; set; }
        public string Medic_Identificacion { get; set; }
        public string Medic_Nombre1 { get; set; }
        public string Medic_Nombre2 { get; set; }
        public string Medic_Apellido1 { get; set; }
        public string Medic_Apellido2 { get; set; }
        public byte[] Medic_Foto { get; set; }
        public byte[] Medic_Huella { get; set; }
        public byte[] Medic_Firma { get; set; }
    }
}
