//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HistoriaClinica_NutricionistaEntities : DbContext
    {
        public HistoriaClinica_NutricionistaEntities()
            : base("name=HistoriaClinica_NutricionistaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<AntecedentePersonal> AntecedentePersonal { get; set; }
        public virtual DbSet<AntecedentesF> AntecedentesF { get; set; }
        public virtual DbSet<AntecedentesP> AntecedentesP { get; set; }
        public virtual DbSet<AntecednteFamiliar> AntecednteFamiliar { get; set; }
        public virtual DbSet<Antropometria> Antropometria { get; set; }
        public virtual DbSet<ARL> ARL { get; set; }
        public virtual DbSet<Atencion_Historia> Atencion_Historia { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Comida> Comida { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Dominancia> Dominancia { get; set; }
        public virtual DbSet<EPS> EPS { get; set; }
        public virtual DbSet<Estado_Atencion> Estado_Atencion { get; set; }
        public virtual DbSet<EstadoCivil> EstadoCivil { get; set; }
        public virtual DbSet<Frecuencia_Consmo> Frecuencia_Consmo { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<HabitoDetalle> HabitoDetalle { get; set; }
        public virtual DbSet<HABITOS> HABITOS { get; set; }
        public virtual DbSet<HistorialPeso> HistorialPeso { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<NivelEducativo> NivelEducativo { get; set; }
        public virtual DbSet<Ocupacion> Ocupacion { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Profesion> Profesion { get; set; }
        public virtual DbSet<Recordatorio> Recordatorio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoDocumento> TipoDocumento { get; set; }
        public virtual DbSet<TipoSangre> TipoSangre { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioModulo> UsuarioModulo { get; set; }
        public virtual DbSet<Historial_Peso> Historial_Peso { get; set; }
        public virtual DbSet<View_Paciente> View_Paciente { get; set; }
        public virtual DbSet<CITAS> CITAS { get; set; }
        public virtual DbSet<ESPECIALIDADES> ESPECIALIDADES { get; set; }
        public virtual DbSet<HORARIOS> HORARIOS { get; set; }
        public virtual DbSet<MEDICOS> MEDICOS { get; set; }
        public virtual DbSet<MEDICOS_ESPECIALIDADES> MEDICOS_ESPECIALIDADES { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
