//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nutricionista
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Paciente
    {
        public string Pac_TipoIdentificacion { get; set; }
        public string Pac_Identificacion { get; set; }
        public string Pac_Nombre1 { get; set; }
        public string Pac_Nombre2 { get; set; }
        public string Pac_Apellido1 { get; set; }
        public string Pac_Apellido2 { get; set; }
        public System.DateTime Pac_FechaNacimiento { get; set; }
        public string Pac_CodGenero { get; set; }
        public string Pac_CodDepto { get; set; }
        public string Pac_CodCiudad { get; set; }
        public string Pac_Direccion { get; set; }
        public int Pac_CodNivelEducativo { get; set; }
        public string Pac_CodProfesion { get; set; }
        public int Pac_TipoSangre { get; set; }
        public int Pac_EstadoCivil { get; set; }
        public string Pac_Telefono { get; set; }
        public byte[] Pac_Foto { get; set; }
        public byte[] Pac_Huella { get; set; }
        public byte[] Pac_Firma { get; set; }
        public int Pac_Dominancia_Codigo { get; set; }
        public Nullable<System.DateTime> Pac_Fecha { get; set; }
        public Nullable<int> Pac_CodEPS { get; set; }
        public Nullable<int> Pac_CodARL { get; set; }
        public int Arl_Codigo { get; set; }
        public string Arl_Descripcion { get; set; }
        public int Eps_Codigo { get; set; }
        public string Eps_Descripcion { get; set; }
        public string Ciud_CodDepto { get; set; }
        public string Ciud_Codigo { get; set; }
        public string Ciud_Nombre { get; set; }
        public string Dept_Codigo { get; set; }
        public string Dept_Nombre { get; set; }
    }
}
